// File: rust/xdp-counter/src/main.rs
//
// Aya userspace: loads the eBPF program, attaches to NIC, polls stats.
//
// BUILD:
//   # Install Rust eBPF toolchain:
//   rustup toolchain install nightly --component rust-src
//   cargo install bpf-linker
//   cargo install cargo-generate   # optional, for scaffolding new Aya projects
//
//   # Build eBPF bytecode first:
//   cargo xtask build-ebpf --release
//
//   # Build userspace:
//   cargo build --release
//
//   # Run:
//   sudo ./target/release/xdp-counter --iface eth0

use anyhow::{bail, Context};
use aya::{
    include_bytes_aligned,
    maps::PerCpuArray,
    programs::{Xdp, XdpFlags},
    Bpf,
};
use aya_log::BpfLogger;
use clap::Parser;
use log::{info, warn};
use std::time::Duration;
use tokio::signal;
use tokio::time;

// ─── CLI ─────────────────────────────────────────────────────────────────────

#[derive(Parser, Debug)]
#[command(version, about = "XDP packet counter using Aya (Rust eBPF)")]
struct Cli {
    /// Network interface to attach to
    #[arg(short, long, default_value = "eth0")]
    iface: String,

    /// Poll interval in seconds
    #[arg(short, long, default_value_t = 2)]
    poll: u64,

    /// Use generic XDP mode (SKB) for compatibility
    #[arg(long)]
    generic: bool,
}

// Must match the eBPF-side definition exactly
#[repr(C)]
#[derive(Copy, Clone, Default)]
struct PacketStats {
    packets: u64,
    bytes:   u64,
    drops:   u64,
}

// ─── Main ─────────────────────────────────────────────────────────────────────

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let cli = Cli::parse();
    env_logger::init();

    // ── Privilege check ──────────────────────────────────────────────────
    if unsafe { libc::geteuid() } != 0 {
        bail!("Must run as root (eBPF requires CAP_BPF + CAP_NET_ADMIN)");
    }

    // ── Load eBPF bytecode ───────────────────────────────────────────────
    //
    // include_bytes_aligned! embeds the .bpf.o at compile time.
    // The path is relative to the workspace root, generated by xtask.
    //
    // This is the core Aya pattern: the .o file is INSIDE the binary.
    // No external files needed at runtime.
    #[cfg(debug_assertions)]
    let bpf_data = include_bytes_aligned!(
        "../../target/bpfel-unknown-none/debug/xdp-counter-ebpf"
    );
    #[cfg(not(debug_assertions))]
    let bpf_data = include_bytes_aligned!(
        "../../target/bpfel-unknown-none/release/xdp-counter-ebpf"
    );

    let mut bpf = Bpf::load(bpf_data).context("Failed to load BPF object")?;

    // ── Set up BPF logging (reads from bpf_printk ring buffer) ──────────
    if let Err(e) = BpfLogger::init(&mut bpf) {
        warn!("BPF logger init failed (non-fatal): {}", e);
    }

    // ── Get and attach XDP program ───────────────────────────────────────
    let program: &mut Xdp = bpf
        .program_mut("xdp_packet_counter")
        .context("Program 'xdp_packet_counter' not found")?
        .try_into()
        .context("Expected XDP program type")?;

    program.load().context("Failed to load XDP program (verifier rejected)")?;

    let flags = if cli.generic {
        XdpFlags::SKB_MODE    // Generic: works on any interface
    } else {
        XdpFlags::default()   // Driver mode if available, falls back to SKB
    };

    program
        .attach(&cli.iface, flags)
        .with_context(|| format!("Failed to attach to interface '{}'", cli.iface))?;

    info!("XDP program attached to '{}'. Press Ctrl+C to stop.", cli.iface);

    // ── Get map reference ────────────────────────────────────────────────
    let mut stats_map: PerCpuArray<_, PacketStats> = PerCpuArray::try_from(
        bpf.map_mut("PROTO_STATS").context("Map 'PROTO_STATS' not found")?
    )?;

    // ── Polling loop ─────────────────────────────────────────────────────
    let mut interval = time::interval(Duration::from_secs(cli.poll));

    let proto_info: &[(__u32, &str)] = &[
        (0,   "TOTAL "),
        (1,   "ICMP  "),
        (6,   "TCP   "),
        (17,  "UDP   "),
        (58,  "ICMPv6"),
        (255, "OTHER "),
    ];

    loop {
        tokio::select! {
            _ = interval.tick() => {
                print!("\x1b[2J\x1b[H");  // clear screen
                println!("=== XDP Packet Counter — {} ===\n", cli.iface);
                println!("{:<10} {:>14} {:>14} {:>12}",
                         "Proto", "Packets", "Bytes", "Drops");
                println!("{}", "-".repeat(52));

                for (key, name) in proto_info {
                    if let Ok(per_cpu_stats) = stats_map.get(*key, 0) {
                        // Aggregate across all CPUs
                        let total = per_cpu_stats.iter().fold(
                            PacketStats::default(),
                            |mut acc, s| {
                                acc.packets += s.packets;
                                acc.bytes   += s.bytes;
                                acc.drops   += s.drops;
                                acc
                            }
                        );
                        println!("{:<10} {:>14} {:>14} {:>12}",
                                 name,
                                 total.packets,
                                 total.bytes,
                                 total.drops);
                    }
                }
            }
            _ = signal::ctrl_c() => {
                info!("Received Ctrl+C, detaching XDP...");
                // Aya automatically detaches when `bpf` is dropped
                break;
            }
        }
    }

    info!("XDP detached from '{}'. Exiting.", cli.iface);
    Ok(())
}

// ─── Cargo.toml content (reference) ──────────────────────────────────────────
//
// [package]
// name = "xdp-counter"
// version = "0.1.0"
// edition = "2021"
//
// [[bin]]
// name = "xdp-counter"
// path = "src/main.rs"
//
// [dependencies]
// aya = { version = "0.13", features = ["async_tokio"] }
// aya-log = "0.2"
// anyhow = "1"
// clap = { version = "4", features = ["derive"] }
// env_logger = "0.11"
// log = "0.4"
// libc = "0.2"
// tokio = { version = "1", features = ["macros", "rt", "rt-multi-thread", "signal", "time"] }
//
// [build-dependencies]
// aya-build = "0.1"