// SPDX-License-Identifier: GPL-2.0
/*
 * xdp_filter.c — Userspace control-plane loader for xdp_filter.bpf.c
 *
 * Responsibilities:
 *   - Load and attach the BPF XDP program to a network interface
 *   - Manage blocklist map (add/remove IPs)
 *   - Poll and display per-CPU stats
 *   - Pin maps under /sys/fs/bpf/xdp_filter/ for persistence
 *   - Clean detach / map unpin on SIGINT/SIGTERM
 *
 * Build:
 *   clang -O2 -g -Wall -o xdp_filter xdp_filter.c \
 *         xdp_filter.skel.h           \   # generated by bpftool
 *         -lbpf -lelf -lz
 *
 * Usage:
 *   sudo ./xdp_filter --iface eth0 --block 192.168.1.100 --stats
 *
 * References:
 *   tools/lib/bpf/  (libbpf source)
 *   samples/bpf/    (kernel tree examples)
 *   Documentation/bpf/libbpf/
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <errno.h>
#include <signal.h>
#include <getopt.h>
#include <arpa/inet.h>          /* inet_pton, htonl  */
#include <net/if.h>             /* if_nametoindex    */
#include <linux/if_link.h>      /* XDP_FLAGS_*       */
#include <bpf/libbpf.h>
#include <bpf/bpf.h>

#include "xdp_filter.skel.h"   /* auto-generated skeleton by: bpftool gen skeleton */

#define BPF_PIN_BASEDIR  "/sys/fs/bpf/xdp_filter"
#define STAT_PASS   0
#define STAT_BLOCK  1
#define STAT_RATE   2
#define STAT_PARSE  3

static volatile int running = 1;
static struct xdp_filter_bpf *skel = NULL;
static int ifindex = -1;

/* ── Signal handler: clean detach ────────────────────────────────────────── */
static void sig_handler(int sig)
{
    (void)sig;
    running = 0;
}

/* ── libbpf log callback: mirrors kernel dev style ───────────────────────── */
static int libbpf_print_fn(enum libbpf_print_level level,
                            const char *format, va_list args)
{
    if (level == LIBBPF_DEBUG)
        return 0;               /* suppress debug noise by default */
    return vfprintf(stderr, format, args);
}

/* ── Block / unblock a single IP ─────────────────────────────────────────── */
static int blocklist_update(int map_fd, const char *ip_str, __u8 value)
{
    __u32 key;
    struct in_addr addr;

    if (inet_pton(AF_INET, ip_str, &addr) != 1) {
        fprintf(stderr, "Invalid IPv4 address: %s\n", ip_str);
        return -EINVAL;
    }

    /*
     * IMPORTANT: store in NETWORK byte order — matches what the BPF
     * program reads from ip->saddr. Do NOT call htonl() here; inet_pton
     * already returns network-order bytes in addr.s_addr.
     */
    key = addr.s_addr;  /* network byte-order */

    if (bpf_map_update_elem(map_fd, &key, &value, BPF_ANY)) {
        perror("bpf_map_update_elem");
        return -errno;
    }
    printf("[blocklist] %s IP %s\n", value ? "BLOCKED" : "UNBLOCKED", ip_str);
    return 0;
}

/* ── Read and sum per-CPU stats array ────────────────────────────────────── */
static __u64 read_percpu_stat(int map_fd, __u32 idx)
{
    int nr_cpus = libbpf_num_possible_cpus();
    __u64 values[nr_cpus];
    __u64 total = 0;

    memset(values, 0, sizeof(values));
    if (bpf_map_lookup_elem(map_fd, &idx, values)) {
        perror("bpf_map_lookup_elem(stats)");
        return 0;
    }
    for (int i = 0; i < nr_cpus; i++)
        total += values[i];
    return total;
}

/* ── Print stats loop ────────────────────────────────────────────────────── */
static void print_stats(int stats_fd)
{
    __u64 pass  = read_percpu_stat(stats_fd, STAT_PASS);
    __u64 block = read_percpu_stat(stats_fd, STAT_BLOCK);
    __u64 rate  = read_percpu_stat(stats_fd, STAT_RATE);
    __u64 parse = read_percpu_stat(stats_fd, STAT_PARSE);

    printf("\r[XDP stats] PASS=%-10llu BLOCK=%-10llu RATE_DROP=%-10llu PARSE_ERR=%-6llu",
           pass, block, rate, parse);
    fflush(stdout);
}

/* ── Pin maps for persistence across process restarts ────────────────────── */
static int pin_maps(struct xdp_filter_bpf *s)
{
    char path[256];
    int  ret;

    mkdir(BPF_PIN_BASEDIR, 0700);   /* ignore EEXIST */

    snprintf(path, sizeof(path), BPF_PIN_BASEDIR "/blocklist");
    ret = bpf_map__pin(s->maps.blocklist, path);
    if (ret && errno != EEXIST) {
        fprintf(stderr, "Failed to pin blocklist: %s\n", strerror(errno));
        return ret;
    }

    snprintf(path, sizeof(path), BPF_PIN_BASEDIR "/rate_map");
    ret = bpf_map__pin(s->maps.rate_map, path);
    if (ret && errno != EEXIST) {
        fprintf(stderr, "Failed to pin rate_map: %s\n", strerror(errno));
        return ret;
    }
    return 0;
}

/* ── Main ────────────────────────────────────────────────────────────────── */
int main(int argc, char **argv)
{
    const char *iface     = NULL;
    const char *block_ip  = NULL;
    const char *unblock_ip = NULL;
    int         show_stats = 0;
    int         skb_mode   = 0;       /* default: native XDP driver mode */
    int         opt;

    static struct option long_opts[] = {
        {"iface",    required_argument, 0, 'i'},
        {"block",    required_argument, 0, 'b'},
        {"unblock",  required_argument, 0, 'u'},
        {"stats",    no_argument,       0, 's'},
        {"skb-mode", no_argument,       0, 'S'},
        {"help",     no_argument,       0, 'h'},
        {0, 0, 0, 0}
    };

    while ((opt = getopt_long(argc, argv, "i:b:u:sSh", long_opts, NULL)) != -1) {
        switch (opt) {
        case 'i': iface      = optarg; break;
        case 'b': block_ip   = optarg; break;
        case 'u': unblock_ip = optarg; break;
        case 's': show_stats = 1;      break;
        case 'S': skb_mode   = 1;      break;
        default:
            fprintf(stderr,
                "Usage: %s --iface <if> [--block <ip>] [--unblock <ip>] "
                "[--stats] [--skb-mode]\n", argv[0]);
            return 1;
        }
    }

    if (!iface) {
        fprintf(stderr, "Error: --iface is required\n");
        return 1;
    }

    ifindex = if_nametoindex(iface);
    if (!ifindex) {
        fprintf(stderr, "Interface '%s' not found\n", iface);
        return 1;
    }

    /* Register signal handlers for clean shutdown */
    signal(SIGINT,  sig_handler);
    signal(SIGTERM, sig_handler);

    libbpf_set_print(libbpf_print_fn);

    /* ── Open and load the BPF object ───────────────────────────────────── */
    skel = xdp_filter_bpf__open_and_load();
    if (!skel) {
        fprintf(stderr, "Failed to open/load BPF skeleton: %s\n", strerror(errno));
        return 1;
    }

    /* Pin maps before attaching so a reload can reuse existing map state */
    if (pin_maps(skel) < 0)
        goto cleanup;

    /* ── Attach XDP program ─────────────────────────────────────────────── */
    DECLARE_LIBBPF_OPTS(bpf_xdp_attach_opts, xdp_opts);
    __u32 flags = skb_mode ? XDP_FLAGS_SKB_MODE : XDP_FLAGS_DRV_MODE;

    /*
     * XDP_FLAGS_DRV_MODE (native): runs in driver interrupt context,
     *   before any memory allocation — lowest latency, highest throughput.
     * XDP_FLAGS_SKB_MODE (generic): runs after skb allocation in generic
     *   stack path — always available, useful for testing on veth/vf.
     */
    if (bpf_xdp_attach(ifindex, bpf_program__fd(skel->progs.xdp_filter_prog),
                        flags, &xdp_opts)) {
        fprintf(stderr, "XDP attach failed on %s: %s\n", iface, strerror(errno));
        goto cleanup;
    }
    printf("[xdp_filter] Attached to %s (ifindex=%d, %s mode)\n",
           iface, ifindex, skb_mode ? "skb/generic" : "native/driver");

    /* ── Block/unblock operations ───────────────────────────────────────── */
    int bl_fd = bpf_map__fd(skel->maps.blocklist);
    if (block_ip)   blocklist_update(bl_fd, block_ip,   1);
    if (unblock_ip) blocklist_update(bl_fd, unblock_ip, 0);

    /* ── Stats polling loop ─────────────────────────────────────────────── */
    if (show_stats) {
        int stats_fd = bpf_map__fd(skel->maps.stats);
        printf("[xdp_filter] Polling stats (Ctrl-C to stop)...\n");
        while (running) {
            print_stats(stats_fd);
            sleep(1);
        }
        printf("\n");
    }

cleanup:
    if (ifindex > 0)
        bpf_xdp_detach(ifindex, flags, &xdp_opts);

    xdp_filter_bpf__destroy(skel);
    printf("[xdp_filter] Detached and cleaned up.\n");
    return 0;
}
