// SPDX-License-Identifier: GPL-2.0-only
/*
 * security_monitor.c — userspace loader, policy manager, event consumer.
 *
 * Lifecycle:
 *   1. Open BPF skeleton (generated by bpftool gen skeleton).
 *   2. Load and verify BPF programs (verifier runs here).
 *   3. Attach LSM hooks.
 *   4. Populate policy maps from config / argv.
 *   5. Poll ringbuf in event loop.
 *   6. On SIGINT: detach, destroy skeleton, exit clean.
 *
 * Build deps:
 *   libbpf ≥ 1.0  (pkg-config --libs libbpf)
 *   Generated:    security_monitor.skel.h  (from bpftool gen skeleton)
 *
 * References:
 *   tools/lib/bpf/libbpf.h
 *   tools/lib/bpf/bpf.h
 *   Documentation/bpf/libbpf/libbpf_overview.rst
 *   samples/bpf/xdp_router_ipv4_user.c  (libbpf pattern reference)
 */

#define _GNU_SOURCE
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <errno.h>
#include <signal.h>
#include <unistd.h>
#include <fcntl.h>
#include <time.h>
#include <sys/stat.h>
#include <sys/resource.h>
#include <bpf/libbpf.h>
#include <bpf/bpf.h>

/* Generated skeleton: bpftool gen skeleton security_monitor.bpf.o > security_monitor.skel.h */
#include "security_monitor.skel.h"
#include "security_monitor.h"

/* ------------------------------------------------------------------ */
/* Globals                                                              */
/* ------------------------------------------------------------------ */
static volatile sig_atomic_t g_stop = 0;

static void sig_handler(int sig) { g_stop = 1; (void)sig; }

/* ------------------------------------------------------------------ */
/* libbpf log callback — route to stderr with level prefix             */
/* ------------------------------------------------------------------ */
static int libbpf_print_fn(enum libbpf_print_level level,
                            const char *format, va_list args)
{
    const char *prefix = (level == LIBBPF_DEBUG)   ? "[DBG] " :
                         (level == LIBBPF_INFO)    ? "[INF] " :
                         (level == LIBBPF_WARN)    ? "[WRN] " : "[ERR] ";
    /*
     * For production: suppress LIBBPF_DEBUG unless -v flag is passed.
     * Here we always print INFO+ and suppress DEBUG for readability.
     */
    if (level == LIBBPF_DEBUG)
        return 0;
    fprintf(stderr, "%s", prefix);
    return vfprintf(stderr, format, args);
}

/* ------------------------------------------------------------------ */
/* Ringbuf event handler — called for every event emitted by BPF       */
/* ------------------------------------------------------------------ */
static int handle_event(void *ctx, void *data, size_t size)
{
    const struct lsm_event *e = data;
    char ts_buf[32];
    struct timespec ts;

    (void)ctx;

    if (size < sizeof(*e)) {
        fprintf(stderr, "[ERR] short event: %zu < %zu\n", size, sizeof(*e));
        return 0;  /* return 0 to keep consuming; non-zero stops ringbuf poll */
    }

    /*
     * Convert BPF monotonic ns to wall-clock for human display.
     * NOTE: this has drift vs bpf_ktime_get_ns() — acceptable for audit logs.
     * For strict correlation use clock_gettime(CLOCK_MONOTONIC) and offset.
     */
    clock_gettime(CLOCK_REALTIME, &ts);
    snprintf(ts_buf, sizeof(ts_buf), "%ld.%06ld",
             (long)ts.tv_sec, ts.tv_nsec / 1000L);

    printf("[%s] %-20s pid=%-7u uid=%-6u gid=%-6u comm=%-16s inode=%u dev=%u\n",
           ts_buf,
           event_type_str(e->event_type),
           e->pid, e->uid, e->gid,
           e->comm,
           e->inode, e->dev);
    fflush(stdout);
    return 0;
}

/* ------------------------------------------------------------------ */
/* Policy population helpers                                            */
/* ------------------------------------------------------------------ */

/*
 * block_file_by_path — stat() the path, extract {inode,dev}, insert into map.
 *
 * Security note: there is a TOCTOU race between stat() and kernel open().
 * This is acceptable for a policy loader (we set policy before workloads run),
 * but for runtime enforcement rely exclusively on the BPF hook, not this helper.
 */
static int block_file_by_path(int map_fd, const char *path, __u8 action)
{
    struct stat sb;
    struct policy_key k;
    int ret;

    if (stat(path, &sb) < 0) {
        fprintf(stderr, "[WRN] stat(%s): %s — skipping policy entry\n",
                path, strerror(errno));
        return -errno;
    }

    k.inode = (__u32)sb.st_ino;
    k.dev   = (__u32)sb.st_dev;

    ret = bpf_map_update_elem(map_fd, &k, &action, BPF_ANY);
    if (ret < 0) {
        fprintf(stderr, "[ERR] map_update blocked_files: %s\n", strerror(-ret));
        return ret;
    }

    printf("[INF] policy: %s %s (inode=%u dev=%u)\n",
           action == POLICY_DENY ? "DENY" : "AUDIT",
           path, k.inode, k.dev);
    return 0;
}

static int block_uid(int map_fd, __u32 uid, __u8 action)
{
    int ret = bpf_map_update_elem(map_fd, &uid, &action, BPF_ANY);
    if (ret < 0)
        fprintf(stderr, "[ERR] map_update blocked_uids uid=%u: %s\n",
                uid, strerror(-ret));
    else
        printf("[INF] policy: UID %u → %s\n",
               uid, action == POLICY_DENY ? "DENY" : "AUDIT");
    return ret;
}

/* ------------------------------------------------------------------ */
/* rlimit bump — required for BPF map memory pre-5.11 kernels          */
/* On 5.11+ memlock rlimit is no longer needed (memcg accounting),     */
/* but bumping it is a harmless no-op on newer kernels.                */
/* ------------------------------------------------------------------ */
static void bump_memlock_rlimit(void)
{
    struct rlimit rlim = { RLIM_INFINITY, RLIM_INFINITY };
    if (setrlimit(RLIMIT_MEMLOCK, &rlim) < 0)
        fprintf(stderr, "[WRN] setrlimit(MEMLOCK): %s\n", strerror(errno));
}

/* ------------------------------------------------------------------ */
/* Print cumulative stats from per-CPU array map                        */
/* ------------------------------------------------------------------ */
static void print_stats(int map_fd)
{
    /* Per-CPU array: value size = ncpus × sizeof(struct hook_stats) */
    int ncpus = libbpf_num_possible_cpus();
    if (ncpus <= 0) return;

    size_t val_sz = (size_t)ncpus * sizeof(struct hook_stats);
    struct hook_stats *vals = calloc((size_t)ncpus, sizeof(struct hook_stats));
    if (!vals) return;

    const char *hook_names[] = {
        [EVENT_EXEC_BLOCKED]     = "exec_blocked",
        [EVENT_FILE_OPEN_DENIED] = "file_open",
        [EVENT_SOCKET_BLOCKED]   = "socket_blocked",
        [EVENT_PTRACE_BLOCKED]   = "ptrace_blocked",
    };

    printf("\n--- BPF LSM Stats ---\n");
    for (__u32 i = 1; i <= 4; i++) {
        if (bpf_map_lookup_elem(map_fd, &i, vals) < 0) continue;

        __u64 total = 0, denied = 0;
        for (int c = 0; c < ncpus; c++) {
            total  += vals[c].total;
            denied += vals[c].denied;
        }
        if (i < 5 && hook_names[i])
            printf("  %-20s total=%-8llu denied=%llu\n",
                   hook_names[i], (unsigned long long)total,
                   (unsigned long long)denied);
    }
    printf("---------------------\n");
    free(vals);
    (void)val_sz;
}

/* ------------------------------------------------------------------ */
/* main                                                                 */
/* ------------------------------------------------------------------ */
int main(int argc, char **argv)
{
    struct security_monitor_bpf *skel = NULL;
    struct ring_buffer *rb = NULL;
    int err;

    /* Setup signal handling before any BPF work */
    signal(SIGINT,  sig_handler);
    signal(SIGTERM, sig_handler);

    /* Route libbpf internal logs to our callback */
    libbpf_set_print(libbpf_print_fn);

    bump_memlock_rlimit();

    /* ---- 1. Open skeleton ----------------------------------------- */
    skel = security_monitor_bpf__open();
    if (!skel) {
        fprintf(stderr, "[ERR] skeleton open failed\n");
        return 1;
    }

    /*
     * Optional: tweak map sizes or program flags BEFORE load.
     * e.g.: skel->maps.events.max_entries = 1 << 20;  // 1 MiB
     * Must be done between open() and load().
     */

    /* ---- 2. Load and verify BPF programs --------------------------- */
    err = security_monitor_bpf__load(skel);
    if (err) {
        fprintf(stderr, "[ERR] skeleton load failed: %d (%s)\n",
                err, strerror(-err));
        goto cleanup;
    }
    printf("[INF] BPF programs loaded and verified\n");

    /* ---- 3. Attach LSM hooks --------------------------------------- */
    err = security_monitor_bpf__attach(skel);
    if (err) {
        fprintf(stderr, "[ERR] skeleton attach failed: %d (%s)\n",
                err, strerror(-err));
        goto cleanup;
    }
    printf("[INF] LSM hooks attached\n");

    /* ---- 4. Populate policy maps ----------------------------------- */
    /*
     * Example policy:
     *   - Block exec of /usr/bin/id (demo — stat it first, get inode)
     *   - Audit (log but allow) opens of /etc/shadow
     *   - Block exec by UID 65534 (nobody)
     *
     * In production: load from a YAML/TOML policy file via a config parser.
     */
    int bf_fd = bpf_map__fd(skel->maps.blocked_files);
    int bu_fd = bpf_map__fd(skel->maps.blocked_uids);

    /* Demo entries — adjust paths to ones that exist on test system */
    block_file_by_path(bf_fd, "/etc/shadow",   POLICY_AUDIT);
    block_file_by_path(bf_fd, "/usr/bin/id",   POLICY_DENY);
    block_uid(bu_fd, 65534, POLICY_DENY);   /* nobody */

    /* ---- 5. Setup ringbuf consumer --------------------------------- */
    rb = ring_buffer__new(bpf_map__fd(skel->maps.events),
                          handle_event, NULL, NULL);
    if (!rb) {
        fprintf(stderr, "[ERR] ring_buffer__new failed\n");
        err = -errno;
        goto cleanup;
    }

    printf("[INF] Monitoring. Press Ctrl+C to stop.\n");

    /* ---- 6. Event loop -------------------------------------------- */
    while (!g_stop) {
        /*
         * ring_buffer__poll() returns:
         *   >0: number of events consumed
         *    0: timeout (100ms here)
         *   <0: error (e.g., -EINTR on signal)
         */
        err = ring_buffer__poll(rb, 100 /* ms timeout */);
        if (err == -EINTR) {
            err = 0;
            break;
        }
        if (err < 0) {
            fprintf(stderr, "[ERR] ring_buffer poll: %d\n", err);
            break;
        }
    }

    /* ---- 7. Print final stats ------------------------------------- */
    print_stats(bpf_map__fd(skel->maps.stats));

cleanup:
    ring_buffer__free(rb);
    security_monitor_bpf__destroy(skel);
    printf("[INF] Detached and cleaned up.\n");
    return err < 0 ? 1 : 0;
}
